on:
  push:
    branches:
      - "main"

env:
  RUST_BACKTRACE: full

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Publish to wasmer/hello -> https://wasmer-hello.wasmer.app
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions/checkout@v3
        with:
          toolchain: stable

      - name: Setup Wasmer
        uses: wasmerio/setup-wasmer@v2
        with:
          version: "v4.2.0"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      # Publish to https://wasmer-hello.wasmer.app
      - name: Publish
        run: wasmer deploy --publish-package --registry https://registry.wasmer.io/graphql --token=${{ secrets.WASMER_CIUSER_PROD_TOKEN }} --non-interactive
